name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  test-local:
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/test-local.yaml
  test-stable:
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/test-stable.yaml
